[env:m5stack-stamps3]
platform = espressif32
board = m5stack-stamps3
framework = arduino

platform_packages =
    framework-arduinoespressif32@https://github.com/espressif/arduino-esp32/releases/download/3.3.6/esp32-core-3.3.6.tar.xz
    framework-arduinoespressif32-libs@https://github.com/espressif/arduino-esp32/releases/download/3.3.6/esp32-core-3.3.6-libs.tar.xz

lib_deps = 
    m5stack/M5Cardputer@^1.0.3
    m5stack/M5Unified@^0.2.5
    https://github.com/wakwak-koba/ESP32-NimBLE-Mouse.git
    mikalhart/TinyGPSPlus

monitor_speed = 115200
build_flags = 
    -DCORE_DEBUG_LEVEL=0
    -DUSE_NIMBLE
    -DARDUINO_USB_CDC_ON_BOOT=1
    -DARDUINO_USB_MODE=1
